project:
  type: website
  output-dir: "."


website:
  title: "Abraham Drury"
  navbar:
    left:
      - text: Home
        file: index.qmd
      - text: CV
        file: cv.qmd
      - text: Research
        file: research.qmd

format:
  html:
    theme: "flatly"
    toc: true