---
title: "Research"
format: html
---


Broadly, I am interested in civil conflict and the strategic decisions made by the participating parties. The decisions made by both the state and rebel organizations are not random and are influenced by the conditions in which the decision is made. Because of this, it is difficult to evaluate the effects of the decision on any outcome within the conflict. For example, evaluating the effects of civilian targeting by the government on conflict duration suffers from significant confounding factors. The decision to target civilians is certainly not random and is likely driven by conditions that will also affect the likelihood of conflict termination. Why the conflict participants opt for certain tactics and strategies is the puzzle I would like to focus my time on. To answer these questions, I am inclined to use cross-national data in order to maximize the generalizability of any answers I reach.

This tab will be updated with relevant content as it becomes available. Thank you for your patience and consideration.